name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa_sign_assign_panel
        chmod 600 ~/.ssh/id_rsa_sign_assign_panel
        ssh-keyscan -H 3.109.198.252 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa_sign_assign_panel ubuntu@3.109.198.252 << EOF
          cd /var/www/html/sign-assign/sign-assign-panel/
          git pull origin main
          npm i
          npm run build
          pm2 reload sign-assign-panel
        EOF